### ISSUE TITLE
Changing chart datalabel opacity at runtime

### ISSUE THREAD

**Issue by solunicansu** [ipax77/pax.BlazorChartJs#10]
Dear team,

I am trying to change the datalabel opacity at runtime but have no luck so far. I am doing this because I have a use case in which I need to change the opacity sometimes.

I tried the following so far but none of the approaches had any effect:

// Trying to change opacity after event
`    private async void PaxChartJsPieChartEventTriggered(ChartJsEvent chartJsEvent)
    {
        if (chartJsEvent is ChartJsInitEvent initEvent)
        {
            chartComponent.ChartJsConfig.Options.Plugins.Datalabels.Opacity = 0.5;
            await chartComponent?.DrawChart();
        }
    }`

// Trying to change opacity in JS after event
`    private async void PaxChartJsPieChartEventTriggered(ChartJsEvent chartJsEvent)
    {
           var module = await moduleTask.Value.ConfigureAwait(false);
            await module.InvokeVoidAsync("setCustomChartOpacity", chartJsConfig.ChartJsConfigGuid)
           .ConfigureAwait(false);
    }`

// JS function try #1
```
export function setCustomChartOpacity(chartId) {
    const chart = Chart.getChart(chartId);
    chart.options.plugins.datalabels.opacity = 0.5;    
    chart.update();
}
```
// JS function try #2
```
export function setCustomChartOpacity(chartId) {
    const chart = Chart.getChart(chartId);
    chart.options.plugins.datalabels.opacity= function(){
    return 0.5; }    
    chart.update();
}
```

Would you potentially have some further ideas what can be tried to achieve the desired scenario?

Thanks a lot and best regards

**Comment by ipax77** [comment]
I wrote a short [test](https://github.com/ipax77/pax.BlazorChartJs/blob/opacitytest/src/pax.BlazorChartJs.samplelib/OpacityChartComp.razor)
It should work 'out of the box'
