### ISSUE TITLE
Add support for time series graphs without having to explicitly import chartjs-adapter-date-fns

### ISSUE THREAD

**Issue by egil** [ipax77/pax.BlazorChartJs#15]
Hi,

This looks like a great library. It would be nice if there were direct support for time series graphs without having to import additional modules and call `ReinitializeChart`.

Perhaps it could also be possible to just specify modules that should be loaded during initialization, like the data labels plugin.

**Comment by egil** [comment]
Ps. this is my current `TimeSeriesChart` component, that wraps all the set up stuff that's needed:

```razor
@using pax.BlazorChartJs
@implements IAsyncDisposable
@inject IJSRuntime jsRuntime
<ChartComponent @ref="ChartComponent" ChartJsConfig="ChartConfig" OnEventTriggered="EventTriggered"></ChartComponent>
@code {
    private Lazy<ValueTask<IJSObjectReference>>? moduleTask;
    private bool isRegistered = false;

    public ChartJsConfig ChartConfig { get; } = new ChartJsConfig()
    {
        Type = pax.BlazorChartJs.ChartType.line,            
    };

    public ChartComponent? ChartComponent { get; private set; }

    protected override void OnInitialized()
    {        
        moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>("import", "https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3/dist/chartjs-adapter-date-fns.bundle.min.js"));
    }

    private async void EventTriggered(ChartJsEvent chartJsEvent)
    {
        if (chartJsEvent is ChartJsInitEvent initEvent)
        {
            await RegisterPlugin();
        }
    }

    private async Task RegisterPlugin()
    {
        if (!isRegistered)
        {
            var module = await moduleTask!.Value;
            isRegistered = true;
            ChartConfig.Data = new ChartJsData()
            {
                Datasets = new List<ChartJsDataset>()
                {
                    new LineDataset() {
                        Label = "My First Dataset",
                        Data = new List<object>()
                        {
                            new { x = "2022-09-07", y = 20 },
                            new { x = "2022-09-08", y = 40 },
                            new { x = "2022-09-09", y = 20 },
                            new { x = "2022-09-10", y = 60 },
                            new { x = "2022-09-11", y = 70 },
                            new { x = "2022-09-12", y = 20 },
                            new { x = "2022-09-13", y = 10 },
                            new { x = "2022-09-14", y = 50 },
                            new { x = "2022-09-15", y = 30 },
                            new { x = "2022-10-01", y = 30 },
                        },
                        Fill = false,
                        BorderColor = "rgb(75, 192, 192)",
                        Tension = 0.1
                    }
                },
            };
            ChartConfig.Options = new ChartJsOptions()
            {
                Scales = new ChartJsOptionsScales()
                {
                    X = new TimeCartesianAxis()
                    {
                        Type = "time",
                        Time = new TimeCartesianAxisTime()
                        {
                            Unit = "minute"
                        }
                    }
                }
            };
            ChartConfig.ReinitializeChart();
        }
    }

    public async ValueTask DisposeAsync()
    {
        if (moduleTask!.IsValueCreated)
        {
            var module = await moduleTask.Value;
            module?.DisposeAsync();
        }
    }
}
```

**Comment by ipax77** [comment]
I added a [sample](https://github.com/ipax77/pax.BlazorChartJs/blob/master/src/pax.BlazorChartJs.samplelib/PreloadPluginChart.razor) with one way to avoid the ReinitializeChart. Another would be to work with css hidden if the point is to avoid the flicker.  

It is not possible to intergrate all available plugins the same way as the data labels plugin. Maybe there is a way to enable a general import of plugins but it might be a security issue if the library is able to load any javascript.

**Comment by egil** [comment]
Thank you @ipax77. A few questions/comments:

1. I have multiple components on screen at the same time that all may show a time series graph (if toggled on), so I am fine with just preloading needed JavaScript once when the app first loads. Is it possible to do that from `_Layouts.cshtml` (I'm using Blazor Server) without it interfering with the BlazorChartJs bootstrapping?

2. I think plugin loading could just work by having the user (me) specify a NPM link to a plugin I want to load, and then pass an anonymous object with any configuration needed to ChartsOptions. When you ask System.Text.Json to serialize an anonymous object, it will just serialize it as is.

Ps. if you enable Discussions in the repo, we can use that for QA instead of issues, if you prefer. I have a few other questions I want to throw your way if possible. Otherwise, I am fine just creating new issues.

**Comment by ipax77** [comment]
I enabled discussions - let's see how it works :)

1.  Loading [multiple charts](https://ipax77.github.io/pax.BlazorChartJs/multiplecharts) does fetch the chart.js file only once (tested with Google Chrome), same with custom plugins
2. I can't think of a clean way to provide a general option at the moment, I've yet to think about it.

I am happy to answer any further questions and will answer them as best I can.
