### ISSUE TITLE
Support for streaming-plugin

### ISSUE THREAD

**Issue by bcheung4589** [ipax77/pax.BlazorChartJs#21]
Hi Pax,

Love the work that you guys are doing here, I want to use this chart for my blazor site where I can load some data and would like to use the streaming-plugin for a nicer chart. Ive looked through the code but couldnt find a corresponding 'Realtime'-property on the ChartJsAxis so Im guessing its not supported yet.

Link to plugin: https://nagix.github.io/chartjs-plugin-streaming/master/samples/charts/line-horizontal.html

Can this be added? And if so, how long would you roughly estimate to have a release?

Again, love the work Im seeing here!

Kind regards,
B.

**Comment by ipax77** [comment]
Hey, thank you for your kind words!
While we cannot guarantee support for every plugin out there, you can customize the ChartJsAxis component to include the 'realtime' object yourself like [here](https://github.com/ipax77/pax.BlazorChartJs/blob/master/src/pax.BlazorChartJs.samplelib/CustomPluginComp.razor)

**Comment by ipax77** [comment]
I tried making [it work](https://github.com/ipax77/pax.BlazorChartJs/blob/chartjs_plugin_streaming/src/pax.BlazorChartJs.samplelib/StreamingChartComp.razor) but I could not get the required adapter to work :(

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of undefined (reading 'DateTime')
      TypeError: Cannot read properties of undefined (reading 'DateTime')
          at https://localhost:7082/_content/pax.BlazorChartJs.samplelib/chartjs-adapter-luxon.min.js:7:303
          at https://localhost:7082/_content/pax.BlazorChartJs.samplelib/chartjs-adapter-luxon.min.js:7:178
          at https://localhost:7082/_content/pax.BlazorChartJs.samplelib/chartjs-adapter-luxon.min.js:7:249
```

**Comment by bcheung4589** [comment]
Hi Pax,

Thanks for looking into it! Ill check it out myself as well, last resort would be a regular line chart.

On another note:
File: https://github.com/ipax77/pax.BlazorChartJs/blob/master/src/pax.BlazorChartJs.samplelib/CustomPluginComp.razor
Line 79: [...] "regsisterPlugin"

Might that be a typo?

**Comment by ipax77** [comment]
Good luck - let me know if you are successful!

Yes, it's a typo - JavaScript always makes me unfocused ;)
