### ISSUE TITLE
Support for Linear Gradients

### ISSUE THREAD

**Issue by markb-collaboratech** [ipax77/pax.BlazorChartJs#36]
Please add support, or provide an example, for using linear gradients for the background of a bar chart bar.

**Comment by ipax77** [comment]
Currently there is no way to pass functions as parameter values. One solution is to write your own javascript like here: [Ticks callback support](https://github.com/ipax77/pax.BlazorChartJs/discussions/30#discussioncomment-7087605)

**Comment by markb-collaboratech** [comment]
Thank you.  I was able to get this working using that idea.
